version: '3.9'
services:
  redis:
    image: redis:8.4
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    env_file: .env
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: '1'
      CHOKIDAR_INTERVAL: '1000'
      NODEMON_LEGACY_WATCH: '1'
    depends_on:
      - redis
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '10'
  automation-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx ts-node src/api/queues/automation.worker.ts
    env_file: .env
    environment:
      CHOKIDAR_USEPOLLING: '1'
      CHOKIDAR_INTERVAL: '1000'
      NODEMON_LEGACY_WATCH: '1'
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
  enrichment-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx ts-node src/api/queues/enrichment.worker.ts
    env_file: .env
    environment:
      CHOKIDAR_USEPOLLING: '1'
      CHOKIDAR_INTERVAL: '1000'
      NODEMON_LEGACY_WATCH: '1'
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  redis_data:
